# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\x12\x08greeting\")\n\x08Greeting\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1f\n\x0fGreetingRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\x10GreetingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2Q\n\x0fGreetingService\x12>\n\x05Greet\x12\x19.greeting.GreetingRequest\x1a\x1a.greeting.GreetingResponseB\x0cZ\n./greetingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\n./greeting'
  _globals['_GREETING']._serialized_start=25
  _globals['_GREETING']._serialized_end=66
  _globals['_GREETINGREQUEST']._serialized_start=68
  _globals['_GREETINGREQUEST']._serialized_end=99
  _globals['_GREETINGRESPONSE']._serialized_start=101
  _globals['_GREETINGRESPONSE']._serialized_end=136
  _globals['_GREETINGSERVICE']._serialized_start=138
  _globals['_GREETINGSERVICE']._serialized_end=219
# @@protoc_insertion_point(module_scope)
